# conda env create -f environment.yml
name: pylidar-tls-canopy
channels:
  - conda-forge
dependencies:
  - python>=3.10
  - numpy
  - numba
  - pandas
  - scipy
  - rasterio
  - tqdm
  - typed-ast
  - jupyterlab
  - ipywidgets
  - ipykernel
  - matplotlib
  - statsmodels
  - cxx-compiler
  - pip
  - pip:
    - -e .
variables:
  RIVLIB_ROOT: /gpfs/data1/vclgp/software/rivlib-2_6_0-x86_64-linux-gcc9
  RDBLIB_ROOT: /gpfs/data1/vclgp/software/rdblib-2.4.0-x86_64-linux
  PYLIDAR_CXX_FLAGS: -std=c++11 
