# conda env create -f environment.yml
name: pylidar-tls-canopy
channels:
  - conda-forge
dependencies:
  - python=3.10
  - numpy
  - numba
  - pandas
  - scipy
  - rasterio
  - tqdm
  - typed-ast
  - jupyterlab
  - ipywidgets
  - ipykernel
  - matplotlib
  - statsmodels
  - pip
  - pip:
    - /Users/armston/Documents/git/pylidar-tls-canopy/rdblib-2.4.1-x86_64-darwin/interface/python/riegl.rdb-2.4.1-cp34.cp35.cp36.cp37.cp38.cp39.cp310-none-macosx_10_9_x86_64.whl 
    - -e .
variables:
  RIVLIB_ROOT: /Users/armston/Documents/git/pylidar-tls-canopy/rivlib-2_6_0-x86_64-linux-gcc11
  PYLIDAR_CXX_FLAGS: -std=c++11 
